sudo: required

before_install:
  - sudo apt-get install cmake

os:
  - windows
  - linux
  
language: 
  - cpp

compiler:
  - gcc
  - clang
script: 
  - cd build && cmake -G "Unix Makefiles" && make -j4 && cd bin && ./cppcore_unittest



