sudo: required

before_install:
  - sudo apt-get install cmake

os:
  - linux
  
language: 
  - cpp

compiler:
  - gcc
  - clang

before_script:
  - cd build && cmake -G "Unix Makefiles" && cd ..

script: 
  - . ./.travis.sh
